mybatis:
  mapper-locations: xml/**/*.xml

spring:
  application:
    name: GreenGramVer1
  datasource:
    url: jdbc:mariadb://localhost/greengram_ver1
    username: root
    password: green502

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    default-model-expand-depth: 10
    default-models-expand-depth: -1
    path: /swagger